import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "the fashion.",
  description: "Generated by create next app",
  icons: "/favicon.svg",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>{children}</body>
    </html>
  );
}
